In [5]:
import pandas as pd
print('Done')

Done

In [6]:
sd=pd.read_csv('_Sales_Data_.csv')
sd

       Order_ID Product        City Quantity Unit_Price  Total_Amount
0         10003  Snacks  Coimbatore        2     214.73           NaN
1         10011  Coffee       Salem        4      30.38        121.52
2         10006  Coffee       Salem        4     471.87       1887.48
3         10011     Tea  Coimbatore        9      90.91           NaN
4         10003  Snacks      Trichy        3      96.61        289.83
...         ...     ...         ...      ...        ...           ...
19995     29996    CAKE     Chennai        2     388.01        776.02
19996     29997  Coffee       Salem        4     474.17       1896.68
19997     29998   juice      Trichy        7        NaN           NaN
19998     29999   Cake      Madurai        6     318.82       1912.92
19999     30000     Tea     Madurai        2     242.85        485.70

[20000 rows x 6 columns]

In [7]:
sd.shape

(20000, 6)

In [8]:
sd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order_ID      20000 non-null  int64
 1   Product       20000 non-null  object
 2   City          19023 non-null  object
 3   Quantity      19359 non-null  object
 4   Unit_Price    19403 non-null  object
 5   Total_Amount  17468 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 937.6+ KB

In [9]:
sd.dtypes

Order_ID          int64
Product          object
City             object
Quantity         object
Unit_Price       object
Total_Amount    float64
dtype: object

#### CHECKING DUPLICATES

In [10]:
sd.duplicated().sum()

np.int64(0)

## DATA CLEANING

In [11]:
sd.isnull().sum()

Order_ID           0
Product            0
City             977
Quantity         641
Unit_Price       597
Total_Amount    2532
dtype: int64

In [12]:
Order=0
Product=0            
City=0             
Quantity=0         
Price=0      
Total=0
s=['UNKNOWN','ERROR']
for i in sd.index:
    if sd.loc[i,'Order_ID'] in s:
      Order+=1
    if sd.loc[i,'Product'] in s:
      Product+=1
    if sd.loc[i,'City'] in s:
      City+=1
    if sd.loc[i,'Quantity'] in s:
      Quantity+=1
    if sd.loc[i,'Unit_Price'] in s:
      Price+=1
    if sd.loc[i,'Total_Amount'] in s:
      Total+=1
print(f'''Count of UNKNOWN ~ 
order    ={Order}
product  ={Product}
city     ={City}
quantity ={Quantity}
price    ={Price}
total    ={Total}''')

Count of UNKNOWN ~
order    =0
product  =392
city     =0
quantity =0
price    =0
total    =0

In [13]:
mode_product = sd["Product"].mode()[0]

for i in sd.index:
    if sd.loc[i, "Product"] == "UNKNOWN":
        sd.loc[i, "Product"] = mode_product

print("Done")

Done

In [14]:
(sd["Product"] == "UNKNOWN").sum()

np.int64(0)

#### After replaced

In [15]:
Order=0
Product=0            
City=0             
Quantity=0         
Price=0      
Total=0
s=['UNKNOWN','ERROR']
for i in sd.index:
    if sd.loc[i,'Order_ID'] in s:
      Order+=1
    if sd.loc[i,'Product'] in s:
      Product+=1
    if sd.loc[i,'City'] in s:
      City+=1
    if sd.loc[i,'Quantity'] in s:
      Quantity+=1
    if sd.loc[i,'Unit_Price'] in s:
      Price+=1
    if sd.loc[i,'Total_Amount'] in s:
      Total+=1
print(f'''Count of UNKNOWN ~ 
order    ={Order}
product  ={Product}
city     ={City}
quantity ={Quantity}
price    ={Price}
total    ={Total}''')

Count of UNKNOWN ~
order    =0
product  =0
city     =0
quantity =0
price    =0
total    =0

#### Replacing temp values

In [16]:
for i in sd.index:
  if sd.loc[i,'Quantity'] in s:
       sd.loc[i,'Quantity']='0'
sd.fillna({'Quantity':'0'},inplace=True)
print('Done')

Done

In [17]:
for i in sd.index:
  if sd.loc[i,'Unit_Price'] in s:
       sd.loc[i,'Unit_Price']='0'
sd.fillna({'Unit_Price':'0'},inplace=True)
print('Done')

Done

In [18]:
for i in sd.index:
  if sd.loc[i,'Total_Amount'] in s:
       sd.loc[i,'Total_Amount']='0'
sd.fillna({'Total_Amount':'0'},inplace=True)
print('Done')

Done

In [19]:
sd.isnull().sum()

Order_ID          0
Product           0
City            977
Quantity          0
Unit_Price        0
Total_Amount      0
dtype: int64

## Standardizing City Names

In [20]:
sd["City"].unique()

array(['Coimbatore', 'Salem', 'Trichy', nan, 'Chenai', 'Madurai',
       'Chennai', 'Madrai', 'chennai'], dtype=object)

In [21]:
sd['City'].str.strip()

0        Coimbatore
1             Salem
2             Salem
3        Coimbatore
4            Trichy
            ...
19995       Chennai
19996         Salem
19997        Trichy
19998       Madurai
19999       Madurai
Name: City, Length: 20000, dtype: object

In [22]:
for i in sd.index:
    if sd.loc[i,'City']=='Chenai'or sd.loc[i,'City']=='chennai':
        sd.loc[i,'City']='Chennai'
    elif sd.loc[i, "City"] == "Madrai":
        sd.loc[i, "City"] = 'Madurai'
print('done')

done

In [23]:
print(sd["City"].unique())

['Coimbatore' 'Salem' 'Trichy' nan 'Chennai' 'Madurai']

In [24]:
sd

       Order_ID Product        City Quantity Unit_Price Total_Amount
0         10003  Snacks  Coimbatore        2     214.73            0
1         10011  Coffee       Salem        4      30.38       121.52
2         10006  Coffee       Salem        4     471.87      1887.48
3         10011     Tea  Coimbatore        9      90.91            0
4         10003  Snacks      Trichy        3      96.61       289.83
...         ...     ...         ...      ...        ...          ...
19995     29996    CAKE     Chennai        2     388.01       776.02
19996     29997  Coffee       Salem        4     474.17      1896.68
19997     29998   juice      Trichy        7          0            0
19998     29999   Cake      Madurai        6     318.82      1912.92
19999     30000     Tea     Madurai        2     242.85        485.7

[20000 rows x 6 columns]

In [25]:
sd['City'].isnull().sum()

np.int64(977)

In [26]:
mode=sd['City'].mode()[0]
mode

'Chennai'

#### Handling Missing Values in City

In [27]:
for i in sd.index:
    if pd.isnull(sd.loc[i,"City"]):
        sd.loc[i,"City"]=mode
print('done')

done

In [28]:
sd['City'].isnull().sum()

np.int64(0)

In [29]:
sd.isnull().sum()

Order_ID        0
Product         0
City            0
Quantity        0
Unit_Price      0
Total_Amount    0
dtype: int64

#### Quantity

In [30]:
sd["Quantity"].unique()

array(['2', '4', '9', '3', '7', '10', '5', '6', '8', '1', '0', 'five',
       '-2'], dtype=object)

In [31]:
for i in sd.index:
    if sd.loc[i, "Quantity"] == "five":
        sd.loc[i, "Quantity"] = '5'
print('done')

done

In [32]:
sd['Quantity']=sd['Quantity'].astype(int)
print('done')

done

In [33]:
sd["Quantity"].unique()

array([ 2,  4,  9,  3,  7, 10,  5,  6,  8,  1,  0, -2])

In [34]:
c=0
for i in sd.index:
    if sd.loc[i,'Quantity']==-2:
        c+=1
print(c)

204

#### Converting negative values into Null

In [35]:
for i in sd.index:
    if sd.loc[i,'Quantity']==-2:
       sd.loc[i,'Quantity']=pd.NA
print('done')

done

In [36]:
sd["Quantity"].unique()

array([ 2.,  4.,  9.,  3.,  7., 10.,  5.,  6.,  8.,  1.,  0., nan])

#### replacing values

In [37]:
median=sd['Quantity'].median()
median

np.float64(5.0)

In [38]:
for i in sd.index:
    if pd.isna(sd.loc[i,'Quantity']) or sd.loc[i,'Quantity']==0:
        sd.loc[i,'Quantity']=median
print('done')

done

#### After

In [39]:
Order=0
Product=0            
City=0             
Quantity=0         
Price=0      
Total=0
for i in sd.index:
    if sd.loc[i,'Order_ID'] =='0':
      Order+=1
    if sd.loc[i,'Product'] =='0':
      Product+=1
    if sd.loc[i,'City'] =='0':
      City+=1
    if sd.loc[i,'Quantity'] ==0:
      Quantity+=1
    if sd.loc[i,'Unit_Price'] =='0':
      Price+=1
    if sd.loc[i,'Total_Amount'] =='0':
      Total+=1
print(f'''Count of zero ~ 
order    ={Order}
product  ={Product}
city     ={City}
quantity ={Quantity}
price    ={Price}
total    ={Total}''')

Count of zero ~
order    =0
product  =0
city     =0
quantity =0
price    =597
total    =2532

#### cleaning Price column

In [40]:
sd["Unit_Price"].unique()

array(['214.73', '30.38', '471.87', ..., '388.01', '474.17', '318.82'],
      shape=(15832,), dtype=object)

In [41]:
print(sd.to_string())

       Order_ID Product        City  Quantity Unit_Price Total_Amount
0         10003  Snacks  Coimbatore       2.0     214.73            0
1         10011  Coffee       Salem       4.0      30.38       121.52
2         10006  Coffee       Salem       4.0     471.87      1887.48
3         10011     Tea  Coimbatore       9.0      90.91            0
4         10003  Snacks      Trichy       3.0      96.61       289.83
5         10006     Tea       Salem       2.0     292.07       584.14
6         10009     Tea     Chennai       7.0     249.35      1745.45
7         10007   juice     Chennai       2.0     300.32       600.64
8         10010     Tea     Madurai       4.0     490.73      1962.92
9         10010  Snacks  Coimbatore      10.0     115.29       1152.9
10        10003     Tea      Trichy       9.0     267.92      2411.28
11        10004   juice     Chennai       5.0      21.67       118.35
12        10006     Tea      Trichy       6.0      88.01       528.06
13        10005  Coffee     Chennai       2.0      59.43       118.86
14        10002   Juice     Chennai       8.0      134.5       1076.0
15        10004   Cake      Chennai      10.0     212.09       2120.9
16        10002  Snacks     Chennai       1.0     327.25       327.25
17        10009    CAKE     Chennai       8.0      72.52       580.16
18        10002  Snacks      Trichy       4.0      29.79       119.16
19        10010     Tea  Coimbatore       7.0     418.82      2931.74
20        10004  Snacks       Salem       9.0      210.2       1891.8
21        10002   juice  Coimbatore      10.0      366.0       3660.0
22        10006   juice     Chennai       5.0     257.85      1289.25
23        10007  Snacks      Trichy       3.0     470.85      1412.55
24        10004    Cake     Madurai      10.0          0            0
25        10026   juice     Madurai       8.0      37.31       298.48
26        10027     Tea     Chennai       1.0     208.28       208.28
27        10028   juice     Madurai       8.0          0            0
28        10029     Tea       Salem       6.0     401.98      2411.88
29        10030   Cake       Trichy       3.0      47.16       141.48
30        10031    CAKE  Coimbatore       9.0       27.4        246.6
31        10032   juice  Coimbatore       9.0     332.64      2993.76
32        10033    Cake  Coimbatore       5.0     321.58       1607.9
33        10034  Coffee     Chennai       1.0     220.37            0
34        10035     Tea  Coimbatore       7.0      263.9       1847.3
35        10036     Tea      Trichy       4.0       28.2        112.8
36        10037     Tea  Coimbatore       5.0     169.75       897.75
37        10038  Coffee       Salem       9.0     311.66      2804.94
38        10039  Snacks     Chennai       9.0     343.24      3089.16
39        10040     Tea       Salem       7.0     185.13      1295.91
40        10041  Coffee  Coimbatore       2.0     285.88       571.76
41        10042   Cake        Salem       6.0     364.63      2187.78
42        10043  Coffee  Coimbatore       2.0     451.63       911.26
43        10044   juice     Chennai      10.0     122.74       1227.4
44        10045  Coffee  Coimbatore      10.0     302.18       3021.8
45        10046  Snacks  Coimbatore       2.0     230.89       461.78
46        10047  Snacks     Chennai       9.0          0            0
47        10048   Cake        Salem       5.0     393.68       1968.4
48        10049     Tea     Chennai       4.0     188.92       755.68
49        10050   Juice  Coimbatore       5.0     437.14       2185.7
50        10051    CAKE     Madurai       5.0     265.65      1328.25
51        10052   juice     Chennai       5.0      410.4       2052.0
52        10053     Tea     Chennai       4.0      171.1        684.4
53        10054   Cake        Salem      10.0     216.92       2169.2
54        10055     Tea  Coimbatore       7.0     204.02      1428.14
55        10056  Coffee  Coimbatore       6.0     228.79      1372.74
56        10057  Snacks       Salem       8.0     159.83      1278.64
57        10058  Snacks      Trichy       7.0     382.81      2679.67
58        10059   Juice     Chennai      10.0     462.58       4625.8
59        10060  Snacks     Chennai       5.0      36.15       180.75
60        10061   juice       Salem       4.0     414.68      1658.72
61        10062    Cake      Trichy       3.0      487.0       1461.0
62        10063  Coffee  Coimbatore       9.0     478.87      4309.83
63        10064     Tea     Chennai       5.0      160.7        803.5
64        10065    Cake     Chennai       6.0     286.26      1717.56
65        10066  Coffee     Chennai       3.0     347.45      1042.35
66        10067     Tea      Trichy       8.0     460.83      3686.64
67        10068   Juice     Madurai       7.0     322.65      2258.55
68        10069   Juice       Salem       9.0     416.32      3746.88
69        10070     Tea       Salem       4.0          0            0
70        10071  Snacks  Coimbatore       5.0     374.01      1870.05
71        10072   juice     Chennai       2.0     136.62       273.24
72        10073  Snacks      Trichy       2.0     175.55        351.1
73        10074    cake       Salem       4.0     474.69      1898.76
74        10075   Juice     Madurai       2.0     499.74       999.48
75        10076    CAKE       Salem       1.0     139.46       139.46
76        10077   Juice  Coimbatore       5.0     391.41      1957.05
77        10078   Cake       Trichy       5.0     458.95            0
78        10079  Coffee     Chennai       1.0     359.38       359.38
79        10080     Tea     Madurai       4.0     281.32      1125.28
80        10081   Juice  Coimbatore       4.0     361.52      1446.08
81        10082   Cake      Madurai       9.0     457.12      4114.08
82        10083  Snacks     Chennai       3.0     133.41       400.23
83        10084     Tea     Chennai       3.0     254.46       763.38
84        10085     Tea      Trichy       8.0     421.33      3370.64
85        10086  Snacks     Chennai       5.0          0            0
86        10087    cake     Madurai       6.0        abc            0
87        10088  Snacks     Chennai       1.0     439.02       439.02
88        10089     Tea      Trichy       9.0     409.96      3689.64
89        10090  Coffee       Salem       9.0     240.96      2168.64
90        10091   juice     Chennai       5.0     268.12       1340.6
91        10092     Tea  Coimbatore       5.0          0            0
92        10093    Cake     Chennai       6.0     276.28      1657.68
93        10094    Cake  Coimbatore       4.0     136.18       544.72
94        10095   Cake        Salem       1.0     300.38       300.38
95        10096  Snacks  Coimbatore       5.0     116.48            0
96        10097   juice     Madurai       3.0     459.99      1379.97
97        10098    Cake     Chennai       3.0     238.05       714.15
98        10099  Snacks       Salem       1.0     465.92       498.92
99        10100   Juice      Trichy       6.0     301.65       1809.9
100       10101  Coffee      Trichy       5.0     453.77      2309.85
101       10102   juice      Trichy       5.0     460.62       2303.1
102       10103    CAKE      Trichy      10.0     202.63       2026.3
103       10104    cake     Chennai       7.0     207.45      1452.15
104       10105    cake     Madurai       7.0      460.6       3224.2
105       10106    Cake     Madurai       1.0     423.89       423.89
106       10107  Snacks     Madurai       5.0     350.57      1752.85
107       10108   Juice     Chennai       5.0     385.68            0
108       10109   Cake       Trichy       9.0     326.27      2936.43
109       10110    Cake       Salem       4.0          0            0
110       10111   Cake        Salem       5.0      28.49       142.45
111       10112  Coffee       Salem       4.0     357.28      1429.12
112       10113  Coffee  Coimbatore      10.0      385.9       3859.0
113       10114     Tea     Madurai       5.0     491.41            0
114       10115   Cake      Madurai      10.0      94.79        947.9
115       10116     Tea     Chennai      10.0     336.97       3415.7
116       10117  Coffee     Madurai       1.0     371.08       371.08
117       10118  Snacks  Coimbatore       7.0      53.03       371.21
118       10119     Tea     Chennai       7.0     120.02       840.14
119       10120  Snacks     Chennai       4.0     293.56      1174.24
120       10121  Coffee      Trichy       6.0      225.0       1350.0
121       10122  Snacks       Salem       5.0          0            0
122       10123     Tea       Salem       9.0     499.48      4495.32
123       10124    cake      Trichy       6.0      20.24       121.44
124       10125   Juice     Chennai       9.0     136.58      1229.22
125       10126  Snacks     Chennai       2.0      34.83        69.66
126       10127  Coffee     Madurai      10.0     233.92       2339.2
127       10128    Cake  Coimbatore       6.0      274.8       1648.8
128       10129     Tea       Salem       5.0      81.18      -162.36
129       10130  Snacks       Salem      10.0       31.6            0
130       10131    CAKE     Chennai       2.0     132.31       264.62
131       10132  Coffee     Madurai       6.0     418.53      2511.18
132       10133  Snacks     Chennai       8.0     391.99      3135.92
133       10134  Snacks       Salem       3.0       27.9         83.7
134       10135   Cake        Salem       5.0      192.2        961.0
135       10136    Cake     Chennai       7.0      145.3       1017.1
136       10137  Coffee     Madurai       2.0     461.48       922.96
137       10138  Snacks  Coimbatore       1.0     485.58       485.58
138       10139   Cake      Chennai       7.0     298.94      2092.58
139       10140   juice     Madurai       3.0      88.66       265.98
140       10141     Tea     Chennai       4.0     387.08      1548.32
141       10142   Juice       Salem       1.0     199.99       199.99
142       10143     Tea      Trichy       3.0      54.49       163.47
143       10144     Tea      Trichy      10.0      47.75        477.5
144       10145  Snacks     Chennai       6.0     431.58      2589.48
145       10146   Juice       Salem       7.0     422.87      2960.09
146       10147    CAKE     Chennai       5.0     254.74       1273.7
147       10148     Tea     Chennai       6.0     398.23      2389.38
148       10149   juice     Madurai       9.0          0            0
149       10150  Coffee  Coimbatore       5.0      83.26            0
150       10151  Snacks       Salem       2.0     267.83       535.66
151       10152   Juice       Salem       4.0      76.17       304.68
152       10153   Juice     Madurai      10.0     345.04            0
153       10154    cake      Trichy       3.0      176.9        530.7
154       10155    Cake     Chennai       5.0     380.45      1902.25
155       10156   Cake       Trichy       7.0     298.56      2089.92
156       10157  Snacks       Salem       9.0     277.09      2493.81
157       10158     Tea     Madurai       6.0     261.26      1567.56
158       10159     Tea     Chennai      10.0      188.5       1885.0
159       10160  Snacks  Coimbatore       1.0      155.7        155.7
160       10161  Snacks     Chennai       5.0      256.5       1282.5
161       10162     Tea       Salem       6.0     258.76      1552.56
162       10163  Snacks       Salem       4.0     431.61      1726.44
163       10164   juice  Coimbatore       7.0     145.42      1017.94
164       10165    Cake       Salem       3.0     164.54       493.62
165       10166   Juice     Chennai       5.0     331.42       1657.1
166       10167   juice       Salem       9.0      98.66       887.94
167       10168  Coffee      Trichy       4.0      72.91       291.64
168       10169  Snacks     Madurai       5.0     168.51       842.55
169       10170     Tea     Madurai       6.0     418.98      2513.88
170       10171  Snacks  Coimbatore      10.0          0            0
171       10172   Juice     Chennai       2.0     135.69       271.38
172       10173   Juice     Madurai       2.0     365.14       730.28
173       10174    cake  Coimbatore       5.0     150.47            0
174       10175  Coffee  Coimbatore       4.0     209.37       837.48
175       10176  Coffee       Salem      10.0     370.36       3703.6
176       10177   juice     Madurai       7.0     386.77      2707.39
177       10178  Snacks     Madurai       3.0      75.32       225.96
178       10179  Snacks       Salem      10.0     493.71       4937.1
179       10180  Coffee  Coimbatore       6.0     139.07       834.42
180       10181  Snacks  Coimbatore       1.0     381.19       381.19
181       10182  Snacks     Madurai       4.0      83.23       332.92
182       10183     Tea      Trichy       8.0     230.87      1846.96
183       10184   juice     Madurai       9.0     245.11      2205.99
184       10185   Juice     Chennai       2.0     369.37       738.74
185       10186    Cake  Coimbatore       3.0     345.52      1036.56
186       10187     Tea     Chennai       2.0      68.28       136.56
187       10188   Juice  Coimbatore       9.0      44.95       404.55
188       10189    cake       Salem       5.0     117.95       589.75
189       10190  Snacks      Trichy       5.0      409.4            0
190       10191  Coffee       Salem       1.0     285.86       285.86
191       10192  Coffee     Chennai      10.0     171.24       1712.4
192       10193    cake     Madurai       8.0      137.0       1096.0
193       10194    Cake       Salem       8.0     287.58      2300.64
194       10195     Tea     Madurai       1.0     458.99            0
195       10196  Coffee       Salem       5.0     231.55            0
196       10197     Tea     Chennai       6.0     207.12      1242.72
197       10198   Juice       Salem       5.0      31.09            0
198       10199   Juice     Madurai       5.0     462.15      2310.75
199       10200     Tea     Chennai       7.0     213.97      1497.79
200       10201  Coffee       Salem       8.0     303.59      2428.72
201       10202   Cake      Madurai       7.0     188.06      1316.42
202       10203  Snacks  Coimbatore       7.0     310.42      2172.94
203       10204  Coffee       Salem       2.0          0            0
204       10205    CAKE      Trichy       5.0          0            0
205       10206   Juice     Madurai      10.0      49.68        496.8
206       10207  Snacks      Trichy       3.0     279.92       839.76
207       10208   Juice       Salem       6.0     141.71       871.26
208       10209    CAKE       Salem       9.0     266.36      2397.24
209       10210  Coffee  Coimbatore      10.0     473.84       4738.4
210       10211    cake       Salem       2.0     362.32       724.64
211       10212     Tea     Madurai      10.0     414.65       4146.5
212       10213     Tea       Salem       2.0     291.15        582.3
213       10214     Tea     Chennai       9.0     371.19      3340.71
214       10215  Coffee     Madurai       4.0      79.36       317.44
215       10216   Cake   Coimbatore       5.0     324.19      1620.95
216       10217  Snacks  Coimbatore       1.0     359.46       359.46
217       10218  Coffee  Coimbatore       1.0     450.28       450.28
218       10219   juice     Chennai       8.0     239.57      1916.56
219       10220   Juice       Salem       3.0     478.06      1434.18
220       10221   Juice     Chennai       6.0     466.75       2800.5
221       10222  Coffee      Trichy       4.0     171.72       686.88
222       10223     Tea      Trichy       3.0      421.7       1265.1
223       10224   juice     Madurai       5.0     119.58            0
224       10225  Coffee      Trichy       2.0        abc            0
225       10226  Coffee  Coimbatore       5.0     421.09            0
226       10227   juice     Chennai       7.0     465.97      3261.79
227       10228  Coffee     Chennai       5.0     288.52            0
228       10229     Tea  Coimbatore       3.0     172.53       517.59
229       10230   Cake      Chennai       9.0       36.9        332.1
230       10231    CAKE     Madurai       4.0     410.11      1640.44
231       10232   juice       Salem       2.0     464.59            0
232       10233     Tea  Coimbatore       6.0     401.59      2409.54
233       10234  Snacks  Coimbatore       7.0     353.44      2474.08
234       10235    cake     Madurai       7.0     190.56      1333.92
235       10236  Coffee       Salem       6.0     117.52       705.12
236       10237   Juice     Chennai       7.0          0            0
237       10238  Coffee     Madurai       2.0      47.22        94.44
238       10239     Tea      Trichy       5.0     309.84       1549.2
239       10240  Snacks     Madurai       9.0      93.99       845.91
240       10241   Cake      Madurai       3.0     148.74       446.22
241       10242   Juice      Trichy      10.0        abc            0
242       10243   Juice       Salem       9.0      149.3       1343.7
243       10244    CAKE     Madurai      10.0     360.19       3601.9
244       10245     Tea      Trichy       9.0       24.8        223.2
245       10246    CAKE      Trichy       8.0     104.86       838.88
246       10247  Snacks     Chennai       4.0     160.76       643.04
247       10248   Juice     Madurai       5.0      94.53       472.65
248       10249  Coffee     Chennai       7.0      25.19            0
249       10250  Coffee  Coimbatore       7.0     469.22      3284.54
250       10251  Snacks     Madurai       5.0      82.49       412.45
251       10252  Snacks      Trichy       3.0      79.57       238.71
252       10253     Tea      Trichy       5.0     137.13            0
253       10254    CAKE       Salem       5.0     161.39       806.95
254       10255    CAKE      Trichy       3.0     486.34      1459.02
255       10256    Cake       Salem       6.0      27.37       164.22
256       10257     Tea     Madurai       8.0     133.59      1068.72
257       10258  Coffee       Salem       4.0     235.75        943.0
258       10259   Juice      Trichy       9.0          0            0
259       10260     Tea     Chennai       9.0     193.92      1745.28
260       10261  Snacks     Madurai       1.0      123.6        123.6
261       10262  Snacks      Trichy       3.0     491.76      1475.28
262       10263     Tea       Salem       7.0     363.23      2542.61
263       10264     Tea       Salem       7.0      58.94       412.58
264       10265  Snacks  Coimbatore      10.0      42.61        426.1
265       10266  Snacks     Chennai      10.0     213.31            0
266       10267   Juice     Chennai      10.0       99.4        994.0
267       10268  Snacks       Salem      10.0     415.84       4158.4
268       10269  Snacks     Madurai       3.0     377.07      1131.21
269       10270    CAKE       Salem       4.0     200.97       803.88
270       10271   Juice     Madurai       4.0          0            0
271       10272     Tea  Coimbatore       2.0     390.95        781.9
272       10273  Coffee     Chennai       6.0     304.69      1828.14
273       10274   Juice       Salem       9.0     227.72      2049.48
274       10275     Tea     Chennai       2.0     419.79       839.58
275       10276  Coffee      Trichy       9.0     208.29      1874.61
276       10277  Snacks  Coimbatore       5.0     485.55      2427.75
277       10278    CAKE  Coimbatore       9.0     442.15      3979.35
278       10279    Cake     Chennai      10.0        abc            0
279       10280     Tea  Coimbatore       2.0        abc            0
280       10281  Coffee      Trichy       6.0     244.47      1466.82
281       10282    cake     Chennai       5.0     186.96        934.8
282       10283  Coffee     Chennai       9.0      76.01       684.09
283       10284   juice     Madurai       7.0     458.04      3206.28

In [97]:
for i in sd.index:
    if sd.loc[i,'Unit_Price']=="abc":
       sd.loc[i,'Unit_Price']='0'
print('done')

done

In [98]:
sd[sd["Unit_Price"] == "abc"]

Empty DataFrame
Columns: [Order_ID, Product, City, Quantity, Unit_Price, Total_Amount]
Index: []

In [99]:
for i in sd.index:
    if sd.loc[i, "Unit_Price"] == "abc":
        sd.loc[i, "Unit_Price"] = 0

sd["Unit_Price"] = sd["Unit_Price"].astype(float)

In [100]:
sd.dtypes

Order_ID          int64
Product          object
City             object
Quantity          int64
Unit_Price      float64
Total_Amount    float64
dtype: object

In [101]:
(sd["Unit_Price"] < 0).sum()

np.int64(0)

In [102]:
price = round(sd["Unit_Price"].mean(), 2)
print(price)

259.64

In [103]:
for i in sd.index:
    if pd.isna(sd.loc[i, "Unit_Price"]) or sd.loc[i, "Unit_Price"]==0:
        sd.loc[i, "Unit_Price"] = price
print('done')

done

In [104]:
sd["Unit_Price"].isnull().sum()

np.int64(0)

In [105]:
(sd["Unit_Price"] == 0).sum()

np.int64(0)

#### cleaning Total column

In [106]:
sd["Total_Amount"] = sd["Total_Amount"].astype(float)

In [107]:
sd.dtypes

Order_ID          int64
Product          object
City             object
Quantity          int64
Unit_Price      float64
Total_Amount    float64
dtype: object

In [108]:
total = sd["Total_Amount"].mean()
print(total)

1400.2393855

In [109]:
for i in sd.index:
    if pd.isna(sd.loc[i, "Total_Amount"]) or sd.loc[i, "Total_Amount"]==0:
        sd.loc[i, "Total_Amount"] = round(sd.loc[i, "Quantity"] * sd.loc[i, "Unit_Price"], 2)

print('done')

done

In [110]:
sd["Total_Amount"].isnull().sum()

np.int64(0)

In [111]:
sd["Total_Amount"].unique

<bound method Series.unique of 0         429.46
1         121.52
2        1887.48
3         818.19
4         289.83
          ...
19995     776.02
19996    1896.68
19997    1747.90
19998    1912.92
19999     485.70
Name: Total_Amount, Length: 20000, dtype: float64>

In [112]:
Order=0
Product=0            
City=0             
Quantity=0         
Price=0      
Total=0
for i in sd.index:
    if sd.loc[i,'Order_ID'] ==0:
      Order+=1
    if sd.loc[i,'Product'] =='0':
      Product+=1
    if sd.loc[i,'City'] =='0':
      City+=1
    if sd.loc[i,'Quantity'] ==0:
      Quantity+=1
    if sd.loc[i,'Unit_Price'] ==0:
      Price+=1
    if sd.loc[i,'Total_Amount'] ==0:
      Total+=1
print(f'''Count of zero ~ 
order    ={Order}
product  ={Product}
city     ={City}
quantity ={Quantity}
price    ={Price}
total    ={Total}''')

Count of zero ~
order    =0
product  =0
city     =0
quantity =0
price    =0
total    =0

In [113]:
print(sd.to_string())

       Order_ID Product        City  Quantity  Unit_Price  Total_Amount
0         10003  Snacks  Coimbatore         2      214.73        429.46
1         10011  Coffee       Salem         4       30.38        121.52
2         10006  Coffee       Salem         4      471.87       1887.48
3         10011     Tea  Coimbatore         9       90.91        818.19
4         10003  Snacks      Trichy         3       96.61        289.83
5         10006     Tea       Salem         2      292.07        584.14
6         10009     Tea     Chennai         7      249.35       1745.45
7         10007   juice     Chennai         2      300.32        600.64
8         10010     Tea     Madurai         4      490.73       1962.92
9         10010  Snacks  Coimbatore        10      115.29       1152.90
10        10003     Tea      Trichy         9      267.92       2411.28
11        10004   juice     Chennai         5       21.67        118.35
12        10006     Tea      Trichy         6       88.01        528.06
13        10005  Coffee     Chennai         2       59.43        118.86
14        10002   Juice     Chennai         8      134.50       1076.00
15        10004   Cake      Chennai        10      212.09       2120.90
16        10002  Snacks     Chennai         1      327.25        327.25
17        10009    CAKE     Chennai         8       72.52        580.16
18        10002  Snacks      Trichy         4       29.79        119.16
19        10010     Tea  Coimbatore         7      418.82       2931.74
20        10004  Snacks       Salem         9      210.20       1891.80
21        10002   juice  Coimbatore        10      366.00       3660.00
22        10006   juice     Chennai         5      257.85       1289.25
23        10007  Snacks      Trichy         3      470.85       1412.55
24        10004    Cake     Madurai        10      249.70       2497.00
25        10026   juice     Madurai         8       37.31        298.48
26        10027     Tea     Chennai         1      208.28        208.28
27        10028   juice     Madurai         8      249.70       1997.60
28        10029     Tea       Salem         6      401.98       2411.88
29        10030   Cake       Trichy         3       47.16        141.48
30        10031    CAKE  Coimbatore         9       27.40        246.60
31        10032   juice  Coimbatore         9      332.64       2993.76
32        10033    Cake  Coimbatore         5      321.58       1607.90
33        10034  Coffee     Chennai         1      220.37        220.37
34        10035     Tea  Coimbatore         7      263.90       1847.30
35        10036     Tea      Trichy         4       28.20        112.80
36        10037     Tea  Coimbatore         5      169.75        897.75
37        10038  Coffee       Salem         9      311.66       2804.94
38        10039  Snacks     Chennai         9      343.24       3089.16
39        10040     Tea       Salem         7      185.13       1295.91
40        10041  Coffee  Coimbatore         2      285.88        571.76
41        10042   Cake        Salem         6      364.63       2187.78
42        10043  Coffee  Coimbatore         2      451.63        911.26
43        10044   juice     Chennai        10      122.74       1227.40
44        10045  Coffee  Coimbatore        10      302.18       3021.80
45        10046  Snacks  Coimbatore         2      230.89        461.78
46        10047  Snacks     Chennai         9      249.70       2247.30
47        10048   Cake        Salem         5      393.68       1968.40
48        10049     Tea     Chennai         4      188.92        755.68
49        10050   Juice  Coimbatore         5      437.14       2185.70
50        10051    CAKE     Madurai         5      265.65       1328.25
51        10052   juice     Chennai         5      410.40       2052.00
52        10053     Tea     Chennai         4      171.10        684.40
53        10054   Cake        Salem        10      216.92       2169.20
54        10055     Tea  Coimbatore         7      204.02       1428.14
55        10056  Coffee  Coimbatore         6      228.79       1372.74
56        10057  Snacks       Salem         8      159.83       1278.64
57        10058  Snacks      Trichy         7      382.81       2679.67
58        10059   Juice     Chennai        10      462.58       4625.80
59        10060  Snacks     Chennai         5       36.15        180.75
60        10061   juice       Salem         4      414.68       1658.72
61        10062    Cake      Trichy         3      487.00       1461.00
62        10063  Coffee  Coimbatore         9      478.87       4309.83
63        10064     Tea     Chennai         5      160.70        803.50
64        10065    Cake     Chennai         6      286.26       1717.56
65        10066  Coffee     Chennai         3      347.45       1042.35
66        10067     Tea      Trichy         8      460.83       3686.64
67        10068   Juice     Madurai         7      322.65       2258.55
68        10069   Juice       Salem         9      416.32       3746.88
69        10070     Tea       Salem         4      249.70        998.80
70        10071  Snacks  Coimbatore         5      374.01       1870.05
71        10072   juice     Chennai         2      136.62        273.24
72        10073  Snacks      Trichy         2      175.55        351.10
73        10074    cake       Salem         4      474.69       1898.76
74        10075   Juice     Madurai         2      499.74        999.48
75        10076    CAKE       Salem         1      139.46        139.46
76        10077   Juice  Coimbatore         5      391.41       1957.05
77        10078   Cake       Trichy         5      458.95       2294.75
78        10079  Coffee     Chennai         1      359.38        359.38
79        10080     Tea     Madurai         4      281.32       1125.28
80        10081   Juice  Coimbatore         4      361.52       1446.08
81        10082   Cake      Madurai         9      457.12       4114.08
82        10083  Snacks     Chennai         3      133.41        400.23
83        10084     Tea     Chennai         3      254.46        763.38
84        10085     Tea      Trichy         8      421.33       3370.64
85        10086  Snacks     Chennai         5      249.70       1248.50
86        10087    cake     Madurai         6      249.70       1498.20
87        10088  Snacks     Chennai         1      439.02        439.02
88        10089     Tea      Trichy         9      409.96       3689.64
89        10090  Coffee       Salem         9      240.96       2168.64
90        10091   juice     Chennai         5      268.12       1340.60
91        10092     Tea  Coimbatore         5      249.70       1248.50
92        10093    Cake     Chennai         6      276.28       1657.68
93        10094    Cake  Coimbatore         4      136.18        544.72
94        10095   Cake        Salem         1      300.38        300.38
95        10096  Snacks  Coimbatore         5      116.48        582.40
96        10097   juice     Madurai         3      459.99       1379.97
97        10098    Cake     Chennai         3      238.05        714.15
98        10099  Snacks       Salem         1      465.92        498.92
99        10100   Juice      Trichy         6      301.65       1809.90
100       10101  Coffee      Trichy         5      453.77       2309.85
101       10102   juice      Trichy         5      460.62       2303.10
102       10103    CAKE      Trichy        10      202.63       2026.30
103       10104    cake     Chennai         7      207.45       1452.15
104       10105    cake     Madurai         7      460.60       3224.20
105       10106    Cake     Madurai         1      423.89        423.89
106       10107  Snacks     Madurai         5      350.57       1752.85
107       10108   Juice     Chennai         5      385.68       1928.40
108       10109   Cake       Trichy         9      326.27       2936.43
109       10110    Cake       Salem         4      249.70        998.80
110       10111   Cake        Salem         5       28.49        142.45
111       10112  Coffee       Salem         4      357.28       1429.12
112       10113  Coffee  Coimbatore        10      385.90       3859.00
113       10114     Tea     Madurai         5      491.41       2457.05
114       10115   Cake      Madurai        10       94.79        947.90
115       10116     Tea     Chennai        10      336.97       3415.70
116       10117  Coffee     Madurai         1      371.08        371.08
117       10118  Snacks  Coimbatore         7       53.03        371.21
118       10119     Tea     Chennai         7      120.02        840.14
119       10120  Snacks     Chennai         4      293.56       1174.24
120       10121  Coffee      Trichy         6      225.00       1350.00
121       10122  Snacks       Salem         5      249.70       1248.50
122       10123     Tea       Salem         9      499.48       4495.32
123       10124    cake      Trichy         6       20.24        121.44
124       10125   Juice     Chennai         9      136.58       1229.22
125       10126  Snacks     Chennai         2       34.83         69.66
126       10127  Coffee     Madurai        10      233.92       2339.20
127       10128    Cake  Coimbatore         6      274.80       1648.80
128       10129     Tea       Salem         5       81.18       -162.36
129       10130  Snacks       Salem        10       31.60        316.00
130       10131    CAKE     Chennai         2      132.31        264.62
131       10132  Coffee     Madurai         6      418.53       2511.18
132       10133  Snacks     Chennai         8      391.99       3135.92
133       10134  Snacks       Salem         3       27.90         83.70
134       10135   Cake        Salem         5      192.20        961.00
135       10136    Cake     Chennai         7      145.30       1017.10
136       10137  Coffee     Madurai         2      461.48        922.96
137       10138  Snacks  Coimbatore         1      485.58        485.58
138       10139   Cake      Chennai         7      298.94       2092.58
139       10140   juice     Madurai         3       88.66        265.98
140       10141     Tea     Chennai         4      387.08       1548.32
141       10142   Juice       Salem         1      199.99        199.99
142       10143     Tea      Trichy         3       54.49        163.47
143       10144     Tea      Trichy        10       47.75        477.50
144       10145  Snacks     Chennai         6      431.58       2589.48
145       10146   Juice       Salem         7      422.87       2960.09
146       10147    CAKE     Chennai         5      254.74       1273.70
147       10148     Tea     Chennai         6      398.23       2389.38
148       10149   juice     Madurai         9      249.70       2247.30
149       10150  Coffee  Coimbatore         5       83.26        416.30
150       10151  Snacks       Salem         2      267.83        535.66
151       10152   Juice       Salem         4       76.17        304.68
152       10153   Juice     Madurai        10      345.04       3450.40
153       10154    cake      Trichy         3      176.90        530.70
154       10155    Cake     Chennai         5      380.45       1902.25
155       10156   Cake       Trichy         7      298.56       2089.92
156       10157  Snacks       Salem         9      277.09       2493.81
157       10158     Tea     Madurai         6      261.26       1567.56
158       10159     Tea     Chennai        10      188.50       1885.00
159       10160  Snacks  Coimbatore         1      155.70        155.70
160       10161  Snacks     Chennai         5      256.50       1282.50
161       10162     Tea       Salem         6      258.76       1552.56
162       10163  Snacks       Salem         4      431.61       1726.44
163       10164   juice  Coimbatore         7      145.42       1017.94
164       10165    Cake       Salem         3      164.54        493.62
165       10166   Juice     Chennai         5      331.42       1657.10
166       10167   juice       Salem         9       98.66        887.94
167       10168  Coffee      Trichy         4       72.91        291.64
168       10169  Snacks     Madurai         5      168.51        842.55
169       10170     Tea     Madurai         6      418.98       2513.88
170       10171  Snacks  Coimbatore        10      249.70       2497.00
171       10172   Juice     Chennai         2      135.69        271.38
172       10173   Juice     Madurai         2      365.14        730.28
173       10174    cake  Coimbatore         5      150.47        752.35
174       10175  Coffee  Coimbatore         4      209.37        837.48
175       10176  Coffee       Salem        10      370.36       3703.60
176       10177   juice     Madurai         7      386.77       2707.39
177       10178  Snacks     Madurai         3       75.32        225.96
178       10179  Snacks       Salem        10      493.71       4937.10
179       10180  Coffee  Coimbatore         6      139.07        834.42
180       10181  Snacks  Coimbatore         1      381.19        381.19
181       10182  Snacks     Madurai         4       83.23        332.92
182       10183     Tea      Trichy         8      230.87       1846.96
183       10184   juice     Madurai         9      245.11       2205.99
184       10185   Juice     Chennai         2      369.37        738.74
185       10186    Cake  Coimbatore         3      345.52       1036.56
186       10187     Tea     Chennai         2       68.28        136.56
187       10188   Juice  Coimbatore         9       44.95        404.55
188       10189    cake       Salem         5      117.95        589.75
189       10190  Snacks      Trichy         5      409.40       2047.00
190       10191  Coffee       Salem         1      285.86        285.86
191       10192  Coffee     Chennai        10      171.24       1712.40
192       10193    cake     Madurai         8      137.00       1096.00
193       10194    Cake       Salem         8      287.58       2300.64
194       10195     Tea     Madurai         1      458.99        458.99
195       10196  Coffee       Salem         5      231.55       1157.75
196       10197     Tea     Chennai         6      207.12       1242.72
197       10198   Juice       Salem         5       31.09        155.45
198       10199   Juice     Madurai         5      462.15       2310.75
199       10200     Tea     Chennai         7      213.97       1497.79
200       10201  Coffee       Salem         8      303.59       2428.72
201       10202   Cake      Madurai         7      188.06       1316.42
202       10203  Snacks  Coimbatore         7      310.42       2172.94
203       10204  Coffee       Salem         2      249.70        499.40
204       10205    CAKE      Trichy         5      249.70       1248.50
205       10206   Juice     Madurai        10       49.68        496.80
206       10207  Snacks      Trichy         3      279.92        839.76
207       10208   Juice       Salem         6      141.71        871.26
208       10209    CAKE       Salem         9      266.36       2397.24
209       10210  Coffee  Coimbatore        10      473.84       4738.40
210       10211    cake       Salem         2      362.32        724.64
211       10212     Tea     Madurai        10      414.65       4146.50
212       10213     Tea       Salem         2      291.15        582.30
213       10214     Tea     Chennai         9      371.19       3340.71
214       10215  Coffee     Madurai         4       79.36        317.44
215       10216   Cake   Coimbatore         5      324.19       1620.95
216       10217  Snacks  Coimbatore         1      359.46        359.46
217       10218  Coffee  Coimbatore         1      450.28        450.28
218       10219   juice     Chennai         8      239.57       1916.56
219       10220   Juice       Salem         3      478.06       1434.18
220       10221   Juice     Chennai         6      466.75       2800.50
221       10222  Coffee      Trichy         4      171.72        686.88
222       10223     Tea      Trichy         3      421.70       1265.10
223       10224   juice     Madurai         5      119.58        597.90
224       10225  Coffee      Trichy         2      249.70        499.40
225       10226  Coffee  Coimbatore         5      421.09       2105.45
226       10227   juice     Chennai         7      465.97       3261.79
227       10228  Coffee     Chennai         5      288.52       1442.60
228       10229     Tea  Coimbatore         3      172.53        517.59
229       10230   Cake      Chennai         9       36.90        332.10
230       10231    CAKE     Madurai         4      410.11       1640.44
231       10232   juice       Salem         2      464.59        929.18
232       10233     Tea  Coimbatore         6      401.59       2409.54
233       10234  Snacks  Coimbatore         7      353.44       2474.08
234       10235    cake     Madurai         7      190.56       1333.92
235       10236  Coffee       Salem         6      117.52        705.12
236       10237   Juice     Chennai         7      249.70       1747.90
237       10238  Coffee     Madurai         2       47.22         94.44
238       10239     Tea      Trichy         5      309.84       1549.20
239       10240  Snacks     Madurai         9       93.99        845.91
240       10241   Cake      Madurai         3      148.74        446.22
241       10242   Juice      Trichy        10      249.70       2497.00
242       10243   Juice       Salem         9      149.30       1343.70
243       10244    CAKE     Madurai        10      360.19       3601.90
244       10245     Tea      Trichy         9       24.80        223.20
245       10246    CAKE      Trichy         8      104.86        838.88
246       10247  Snacks     Chennai         4      160.76        643.04
247       10248   Juice     Madurai         5       94.53        472.65
248       10249  Coffee     Chennai         7       25.19        176.33
249       10250  Coffee  Coimbatore         7      469.22       3284.54
250       10251  Snacks     Madurai         5       82.49        412.45
251       10252  Snacks      Trichy         3       79.57        238.71
252       10253     Tea      Trichy         5      137.13        685.65
253       10254    CAKE       Salem         5      161.39        806.95
254       10255    CAKE      Trichy         3      486.34       1459.02
255       10256    Cake       Salem         6       27.37        164.22
256       10257     Tea     Madurai         8      133.59       1068.72
257       10258  Coffee       Salem         4      235.75        943.00
258       10259   Juice      Trichy         9      249.70       2247.30
259       10260     Tea     Chennai         9      193.92       1745.28
260       10261  Snacks     Madurai         1      123.60        123.60
261       10262  Snacks      Trichy         3      491.76       1475.28
262       10263     Tea       Salem         7      363.23       2542.61
263       10264     Tea       Salem         7       58.94        412.58
264       10265  Snacks  Coimbatore        10       42.61        426.10
265       10266  Snacks     Chennai        10      213.31       2133.10
266       10267   Juice     Chennai        10       99.40        994.00
267       10268  Snacks       Salem        10      415.84       4158.40
268       10269  Snacks     Madurai         3      377.07       1131.21
269       10270    CAKE       Salem         4      200.97        803.88
270       10271   Juice     Madurai         4      249.70        998.80
271       10272     Tea  Coimbatore         2      390.95        781.90
272       10273  Coffee     Chennai         6      304.69       1828.14
273       10274   Juice       Salem         9      227.72       2049.48
274       10275     Tea     Chennai         2      419.79        839.58
275       10276  Coffee      Trichy         9      208.29       1874.61

### Saving the Cleaned Dataset

In [114]:
sd.to_csv('Sales__Data.csv',index=False)

In [115]:
sd.head(20)

    Order_ID Product        City  Quantity  Unit_Price  Total_Amount
0      10003  Snacks  Coimbatore         2      214.73        429.46
1      10011  Coffee       Salem         4       30.38        121.52
2      10006  Coffee       Salem         4      471.87       1887.48
3      10011     Tea  Coimbatore         9       90.91        818.19
4      10003  Snacks      Trichy         3       96.61        289.83
5      10006     Tea       Salem         2      292.07        584.14
6      10009     Tea     Chennai         7      249.35       1745.45
7      10007   juice     Chennai         2      300.32        600.64
8      10010     Tea     Madurai         4      490.73       1962.92
9      10010  Snacks  Coimbatore        10      115.29       1152.90
10     10003     Tea      Trichy         9      267.92       2411.28
11     10004   juice     Chennai         5       21.67        118.35
12     10006     Tea      Trichy         6       88.01        528.06
13     10005  Coffee     Chennai         2       59.43        118.86
14     10002   Juice     Chennai         8      134.50       1076.00
15     10004   Cake      Chennai        10      212.09       2120.90
16     10002  Snacks     Chennai         1      327.25        327.25
17     10009    CAKE     Chennai         8       72.52        580.16
18     10002  Snacks      Trichy         4       29.79        119.16
19     10010     Tea  Coimbatore         7      418.82       2931.74